/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedVoteArenaImport } from './routes/_protected/vote-arena'
import { Route as ProtectedStartupsImport } from './routes/_protected/startups'
import { Route as ProtectedNetworkImport } from './routes/_protected/network'
import { Route as ProtectedMessageImport } from './routes/_protected/message'
import { Route as ProtectedHomeImport } from './routes/_protected/home'
import { Route as ProtectedCrowdfundingImport } from './routes/_protected/crowdfunding'
import { Route as ProtectedMessageIndexImport } from './routes/_protected/message.index'
import { Route as ProtectedStartupsStartupidImport } from './routes/_protected/startups.$startupid'
import { Route as ProtectedProfileUsernameImport } from './routes/_protected/profile.$username'
import { Route as ProtectedMessageUsernameImport } from './routes/_protected/message.$username'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedVoteArenaRoute = ProtectedVoteArenaImport.update({
  id: '/vote-arena',
  path: '/vote-arena',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedStartupsRoute = ProtectedStartupsImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedNetworkRoute = ProtectedNetworkImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedMessageRoute = ProtectedMessageImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedHomeRoute = ProtectedHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedCrowdfundingRoute = ProtectedCrowdfundingImport.update({
  id: '/crowdfunding',
  path: '/crowdfunding',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedMessageIndexRoute = ProtectedMessageIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedMessageRoute,
} as any)

const ProtectedStartupsStartupidRoute = ProtectedStartupsStartupidImport.update(
  {
    id: '/$startupid',
    path: '/$startupid',
    getParentRoute: () => ProtectedStartupsRoute,
  } as any,
)

const ProtectedProfileUsernameRoute = ProtectedProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedMessageUsernameRoute = ProtectedMessageUsernameImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProtectedMessageRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_protected/crowdfunding': {
      id: '/_protected/crowdfunding'
      path: '/crowdfunding'
      fullPath: '/crowdfunding'
      preLoaderRoute: typeof ProtectedCrowdfundingImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/message': {
      id: '/_protected/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof ProtectedMessageImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/network': {
      id: '/_protected/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof ProtectedNetworkImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/startups': {
      id: '/_protected/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof ProtectedStartupsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/vote-arena': {
      id: '/_protected/vote-arena'
      path: '/vote-arena'
      fullPath: '/vote-arena'
      preLoaderRoute: typeof ProtectedVoteArenaImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/message/$username': {
      id: '/_protected/message/$username'
      path: '/$username'
      fullPath: '/message/$username'
      preLoaderRoute: typeof ProtectedMessageUsernameImport
      parentRoute: typeof ProtectedMessageImport
    }
    '/_protected/profile/$username': {
      id: '/_protected/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProtectedProfileUsernameImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/startups/$startupid': {
      id: '/_protected/startups/$startupid'
      path: '/$startupid'
      fullPath: '/startups/$startupid'
      preLoaderRoute: typeof ProtectedStartupsStartupidImport
      parentRoute: typeof ProtectedStartupsImport
    }
    '/_protected/message/': {
      id: '/_protected/message/'
      path: '/'
      fullPath: '/message/'
      preLoaderRoute: typeof ProtectedMessageIndexImport
      parentRoute: typeof ProtectedMessageImport
    }
  }
}

// Create and export the route tree

interface ProtectedMessageRouteChildren {
  ProtectedMessageUsernameRoute: typeof ProtectedMessageUsernameRoute
  ProtectedMessageIndexRoute: typeof ProtectedMessageIndexRoute
}

const ProtectedMessageRouteChildren: ProtectedMessageRouteChildren = {
  ProtectedMessageUsernameRoute: ProtectedMessageUsernameRoute,
  ProtectedMessageIndexRoute: ProtectedMessageIndexRoute,
}

const ProtectedMessageRouteWithChildren =
  ProtectedMessageRoute._addFileChildren(ProtectedMessageRouteChildren)

interface ProtectedStartupsRouteChildren {
  ProtectedStartupsStartupidRoute: typeof ProtectedStartupsStartupidRoute
}

const ProtectedStartupsRouteChildren: ProtectedStartupsRouteChildren = {
  ProtectedStartupsStartupidRoute: ProtectedStartupsStartupidRoute,
}

const ProtectedStartupsRouteWithChildren =
  ProtectedStartupsRoute._addFileChildren(ProtectedStartupsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedCrowdfundingRoute: typeof ProtectedCrowdfundingRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedMessageRoute: typeof ProtectedMessageRouteWithChildren
  ProtectedNetworkRoute: typeof ProtectedNetworkRoute
  ProtectedStartupsRoute: typeof ProtectedStartupsRouteWithChildren
  ProtectedVoteArenaRoute: typeof ProtectedVoteArenaRoute
  ProtectedProfileUsernameRoute: typeof ProtectedProfileUsernameRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCrowdfundingRoute: ProtectedCrowdfundingRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedMessageRoute: ProtectedMessageRouteWithChildren,
  ProtectedNetworkRoute: ProtectedNetworkRoute,
  ProtectedStartupsRoute: ProtectedStartupsRouteWithChildren,
  ProtectedVoteArenaRoute: ProtectedVoteArenaRoute,
  ProtectedProfileUsernameRoute: ProtectedProfileUsernameRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/crowdfunding': typeof ProtectedCrowdfundingRoute
  '/home': typeof ProtectedHomeRoute
  '/message': typeof ProtectedMessageRouteWithChildren
  '/network': typeof ProtectedNetworkRoute
  '/startups': typeof ProtectedStartupsRouteWithChildren
  '/vote-arena': typeof ProtectedVoteArenaRoute
  '/message/$username': typeof ProtectedMessageUsernameRoute
  '/profile/$username': typeof ProtectedProfileUsernameRoute
  '/startups/$startupid': typeof ProtectedStartupsStartupidRoute
  '/message/': typeof ProtectedMessageIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/crowdfunding': typeof ProtectedCrowdfundingRoute
  '/home': typeof ProtectedHomeRoute
  '/network': typeof ProtectedNetworkRoute
  '/startups': typeof ProtectedStartupsRouteWithChildren
  '/vote-arena': typeof ProtectedVoteArenaRoute
  '/message/$username': typeof ProtectedMessageUsernameRoute
  '/profile/$username': typeof ProtectedProfileUsernameRoute
  '/startups/$startupid': typeof ProtectedStartupsStartupidRoute
  '/message': typeof ProtectedMessageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/crowdfunding': typeof ProtectedCrowdfundingRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/message': typeof ProtectedMessageRouteWithChildren
  '/_protected/network': typeof ProtectedNetworkRoute
  '/_protected/startups': typeof ProtectedStartupsRouteWithChildren
  '/_protected/vote-arena': typeof ProtectedVoteArenaRoute
  '/_protected/message/$username': typeof ProtectedMessageUsernameRoute
  '/_protected/profile/$username': typeof ProtectedProfileUsernameRoute
  '/_protected/startups/$startupid': typeof ProtectedStartupsStartupidRoute
  '/_protected/message/': typeof ProtectedMessageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/crowdfunding'
    | '/home'
    | '/message'
    | '/network'
    | '/startups'
    | '/vote-arena'
    | '/message/$username'
    | '/profile/$username'
    | '/startups/$startupid'
    | '/message/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/crowdfunding'
    | '/home'
    | '/network'
    | '/startups'
    | '/vote-arena'
    | '/message/$username'
    | '/profile/$username'
    | '/startups/$startupid'
    | '/message'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/crowdfunding'
    | '/_protected/home'
    | '/_protected/message'
    | '/_protected/network'
    | '/_protected/startups'
    | '/_protected/vote-arena'
    | '/_protected/message/$username'
    | '/_protected/profile/$username'
    | '/_protected/startups/$startupid'
    | '/_protected/message/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/crowdfunding",
        "/_protected/home",
        "/_protected/message",
        "/_protected/network",
        "/_protected/startups",
        "/_protected/vote-arena",
        "/_protected/profile/$username"
      ]
    },
    "/_protected/crowdfunding": {
      "filePath": "_protected/crowdfunding.tsx",
      "parent": "/_protected"
    },
    "/_protected/home": {
      "filePath": "_protected/home.tsx",
      "parent": "/_protected"
    },
    "/_protected/message": {
      "filePath": "_protected/message.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/message/$username",
        "/_protected/message/"
      ]
    },
    "/_protected/network": {
      "filePath": "_protected/network.tsx",
      "parent": "/_protected"
    },
    "/_protected/startups": {
      "filePath": "_protected/startups.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/startups/$startupid"
      ]
    },
    "/_protected/vote-arena": {
      "filePath": "_protected/vote-arena.tsx",
      "parent": "/_protected"
    },
    "/_protected/message/$username": {
      "filePath": "_protected/message.$username.tsx",
      "parent": "/_protected/message"
    },
    "/_protected/profile/$username": {
      "filePath": "_protected/profile.$username.tsx",
      "parent": "/_protected"
    },
    "/_protected/startups/$startupid": {
      "filePath": "_protected/startups.$startupid.tsx",
      "parent": "/_protected/startups"
    },
    "/_protected/message/": {
      "filePath": "_protected/message.index.tsx",
      "parent": "/_protected/message"
    }
  }
}
ROUTE_MANIFEST_END */
